### ISSUE TITLE
help me survive

### ISSUE THREAD

**Issue by eatgrass** [teambition/Survival-Guide#1]
really want to know more about teambition, actually, i have an interview on tuesday for the position of nodejs developer, please update this awesome repo, thanks a million! :+1:

**Comment by winduser** [comment]
Well. We plan to commit our guide on salary and perks firstly. I would be glad if our first guide benefits to you. 

By the way, looking forward to seeing you in Teambition.

**Comment by eatgrass** [comment]
Thanks @winduser, hope I am qualified.
